import type { Metadata } from "next";
import "./globals.css";

import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import MainHeader from "@/components/main-header";

import MainNavigation from "@/components/main-navigation";

const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};
import {
	Archive,
	ArchiveX,
	File,
	Inbox,
	LucideIcon,
	Send,
	Trash2,
} from "lucide-react";
const links: {
	title: string;
	label?: string | undefined;
	icon: LucideIcon;
	variant: "default" | "ghost";
}[] = [
	{
		title: "Inbox",
		label: "128",
		icon: Inbox,
		variant: "default",
	},
	{
		title: "Drafts",
		label: "9",
		icon: File,
		variant: "ghost",
	},
	{
		title: "Sent",
		label: "",
		icon: Send,
		variant: "ghost",
	},
	{
		title: "Junk",
		label: "23",
		icon: ArchiveX,
		variant: "ghost",
	},
	{
		title: "Trash",
		label: "",
		icon: Trash2,
		variant: "ghost",
	},
	{
		title: "Archive",
		label: "",
		icon: Archive,
		variant: "ghost",
	},
];

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={cn(
					"min-h-screen w-full bg-background font-sans antialiased",
					fontSans.variable
				)}
			>
				<div className="grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]">
					<div className="hidden border-r bg-muted/40 md:block">
						<MainNavigation isCollapsed={false} links={links} />
					</div>
					<div className="flex flex-col">
						<MainHeader />
						{children}
					</div>
				</div>
			</body>
		</html>
	);
}
