import type { Metadata } from "next";
import "./globals.css";

import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import MainHeader from "@/components/main-header";
import MainNavigation from "@/components/main-navigation";
import {
	ResizableHandle,
	ResizablePanel,
	ResizablePanelGroup,
} from "@/components/ui/resizable";

const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};
import {
	Archive,
	ArchiveX,
	Calendar,
	File,
	Inbox,
	LucideIcon,
	MessageCircle,
	MessageSquareText,
	Send,
	Trash2,
	Users,
} from "lucide-react";
const links: {
	title: string;
	label?: string | undefined;
	href: string;
	icon: LucideIcon;
	variant: "default" | "ghost";
}[] = [
	{
		title: "Activity",
		label: "128",
		href: "/",
		icon: Inbox,
		variant: "default",
	},
	{
		title: "Community",
		label: "9",
		href: "/community",
		icon: Users,
		variant: "ghost",
	},
	{
		title: "Chat",
		label: "",
		href: "/chat",
		icon: MessageCircle,
		variant: "ghost",
	},
	{
		title: "Calendar",
		label: "23",
		href: "/calendar",
		icon: Calendar,
		variant: "ghost",
	},
	{
		title: "Meetings",
		label: "",
		href: "/meetings",
		icon: MessageSquareText,
		variant: "ghost",
	},
	{
		title: "Archive",
		label: "",
		href: "/archive",
		icon: Archive,
		variant: "ghost",
	},
];

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={cn(
					"min-h-screen w-full bg-background font-sans antialiased",
					fontSans.variable
				)}
			>
				<ResizablePanelGroup
					direction="horizontal"
					className="min-h-[200px] max-w-full rounded-lg border items-stretch"
				>
					<div className="grid min-h-screen w-full  md:grid-cols-[220px_0px_1fr] lg:grid-cols-[280px_0px_1fr]">
						<ResizablePanel
							defaultSize={25}
							collapsedSize={4}
							collapsible={true}
							// minSize={15}
							// maxSize={20}
							// onCollapse={(collapsed) => {
							// 	setIsCollapsed(collapsed);
							// 	document.cookie = `react-resizable-panels:collapsed=${JSON.stringify(
							// 		collapsed
							// 	)}`;
							// }}
						>
							<div className="hidden h-full border-r bg-muted/40 md:block">
								<MainNavigation isCollapsed={false} links={links} />
							</div>
						</ResizablePanel>
						<ResizableHandle withHandle />
						<ResizablePanel defaultSize={75}>
							<div className="h-full flex flex-col">
								<MainHeader />
								{children}
							</div>
						</ResizablePanel>
					</div>
				</ResizablePanelGroup>
			</body>
		</html>
	);
}
